blueprint:
  name: Toggle light on time
  description: Turn on of off lights based on the time (start and end). Use a helper conversion for switch devices.
  domain: automation
  author: igresc
  source_url: https://github.com/igresc/ha-blueprints/blob/main/time_schedule_lighting_automation.yaml
  input:
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    time_on:
      name: Time On
      description: Time to turn on lights.
      selector:
        time:
    time_off:
      name: Time Off
      description: Time to turn off lights.
      selector:
        time:

alias: Light Time schedule
description: ''
trigger:
- platform: time
  at: !input time_on
  id: time_on
- platform: time
  at: !input time_off
  id: time_off
condition: []
action:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id:
        - time_on
      - condition: time
        after: !input time_on
        before: !input time_off
    sequence:
    - service: light.turn_on
      target: !input light_target
  default:
    - service: light.turn_off
      target: !input light_target
mode: single